import axios from "axios";
const api=axios.create({
    baseURL: "http://localhost:3000",
    withCredentials: true
});


/**
 * @description Service to generate interview report based on user self description, resume and job description.
 * @param {Object} params
 * @param {String} params.jobDescription - Job description provided by the user.
 * @param {String} params.selfDescription - Self description provided by the user.
 * @param {String} params.resume - Resume content extracted from the uploaded PDF file.
 * @returns {Object} Interview report generated by the backend.
 */

export const generateInterviewReport= async ({jobDescription, selfDescription, resume})=>{
    const formData=new FormData()
    formData.append("jobDescription", jobDescription)
    formData.append("selfDescription", selfDescription)
    // If `resume` is a File (from input.files[0]) append it directly, otherwise treat as blob
    if (resume instanceof File) {
        formData.append("resume", resume)
    } else if (resume) {
        formData.append("resume", new Blob([resume], { type: "application/pdf" }), "resume.pdf")
    }
    
    const response=await api.post("/api/interview/report", formData, {
        headers: {
            "Content-Type": "multipart/form-data"
        }
    });
    return response.data;
};


/** * @description Service to get interview report by interviewId.
 * @param {String} interviewId - ID of the interview report to fetch.
 * @returns {Object} Interview report fetched from the backend.
 */

export const getInterviewReportById=async (interviewId)=>{
    const response=await api.get(`/api/interview/report/${interviewId}`);
    return response.data;
}

/**
 * @description Service to get all interview reports of logged in user.
 * @returns {Array} List of interview reports fetched from the backend.
 */
export const getAllInterviewReports=async ()=>{
    const response=await api.get("/api/interview/reports");
    return response.data;
}

